name: EnchantViewer
version: 1.0
main: com.example.enchantviewer.EnchantViewer
api-version: 1.21
author: Gemini
depend: [MMOItems]
description: Get enchantments from a player's held item.
commands:
  getenchants:
    description: Gets enchantments from a player's held item via command.
    usage: /<command> <player> <mainhand|offhand>
    permission: enchantviewer.use
  enchmigrate:
    description: Opens the enchantment migration GUI.
    usage: /<command>
    permission: enchantviewer.gui
  nbtinfo:
    description: Prints the NBT data of the held item to the console.
    usage: /<command>
    permission: enchantviewer.use
